### ISSUE TITLE
Начальный запуск

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder-reports#1]
Пробую собрать и запустить сервис.
fork, git clone, npm install

```bash
~/Work/Git/windowbuilder-reports$ node ./scripts/build.js
(node:15655) UnhandledPromiseRejectionWarning: Error: Could not resolve '../../src/metadata/chartscharacteristics' from server/metadata/modifiersNew.js
    at error (/home/suhov/Work/Git/windowbuilder-reports/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/home/suhov/Work/Git/windowbuilder-reports/node_modules/rollup/dist/rollup.js:18244:8)
    at <anonymous>
(node:15655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.jsprocess with a non-zero exit code.
```
Ему действительно что-то не хватает или мне надо сделать мягкие ссылки на windowbuilder чтобы они пользовались одними данными?

В `src`   `metadata`  нет вообще.

**Comment by unpete** [comment]
Нужны ссылки на папки wb.
Не знал, что ссылки ln - мягкие.

**Comment by Sehktel** [comment]
> Не знал, что ссылки ln - мягкие.

Точно, символические! :-) Помню что одни жесткие, а вторые получились мягкие :-)
Ссылки создам, отпишусь.

**Comment by Sehktel** [comment]
До создания ссылок руки еще не дошли. 
Пока решил поступить проще - взять готовый код с сервера. 
Скопировал, создал переменные окружения. 
Запустил.
Все хорошо, сервер ждет подключения, вот только на localhost IPv6 ...

Сделать ссылки или попробовать отучить node js использовать ipv6 ?

**Comment by unpete** [comment]
Штатно, koa слушает на всех ip. И v4 и v6. Что в этом плохого?

**Comment by Sehktel** [comment]
Я не в коем разе. Мне понять направление движения.

**Comment by Sehktel** [comment]
Отписываюсь о результатах 
Пока копия с сервера windowbuilder-reports которой смотрит на мой couchdb.
Настроен на localhost (127.0.0.1), и заданный порт (4000).
Собственно можно сейчас перевести, чтобы он все настройки брал из переменных окружения.
Отладка цепляется как nodejs так и хромом. 
Собственно у нас получается index.js, который и запускается на исполнение. 

Следующий шаг - собрать сервис самостоятельно, благо "эталон" для сравнения имеется.
